### ISSUE TITLE
Make the navbar color uniformed to the app

### ISSUE THREAD

**Issue by Jnss98b** [enricocid/VectorifyDaHome#4]
Just a minor cosmetic change. You could either extend the app to the navbar and make it transparent for Android 10 compatibility or just simply change the navbar color, your call.

![Screenshot_20190914-233119](https://user-images.githubusercontent.com/24306400/64916218-d5bb9100-d747-11e9-87c7-604985d2620b.jpg)

**Comment by Jnss98b** [comment]
Even better, you could extend the app edge to edge (which mean the status bar color should be uniformed too

**Comment by Jnss98b** [comment]
This is way more annoying in dark mode

![Screenshot_20191130-224016](https://user-images.githubusercontent.com/24306400/69909038-7ffb9a00-13c2-11ea-8471-ebc24ca7421c.jpg)

**Comment by enricocid** [comment]
Don't worry,once finished with MPGO I will improve theme also for VDH implementing day night and edge to edge (^^)

**Comment by Jnss98b** [comment]
Alright, thanks for acknowledging it

**Comment by enricocid** [comment]
![Screenshot_20191204-090534](https://user-images.githubusercontent.com/7274841/70124623-85ccd600-1675-11ea-824b-12b0eb95021c.png)


Gonna push within today the update. Thanks for Your contribution on this improvement on MPGO and VDH 😁👌

**Comment by Jnss98b** [comment]
> day night theme is still in beta sadly

I don't see a beta sign up on the play store listing

**Comment by enricocid** [comment]
No no, I meant it is still not available in material components library 1.0.0. Actually day night theme is only available since 1.1.0- alpha01. Latest version of the version is 1.2.0-alpha02. Anyway I have to use the stable release 1.0.0 that does not contain a day night theme.
A solution could be to use AppCompat theme but then bottom bar wouldn't work. So have to wait it will be released to stable channel 😉
